name: Publish Docker
on:
  push:
    branches:
      - main
      - dev
env:
  BUILD_CONTAINER_IMAGE: xmtplabs/xmtp-inbox-web:latest
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - uses: actions/checkout@v3
      - run: docker/build
        env:
          INFURA_ID: ${{ secrets.DEV_INFURA_ID }}
      - run: docker/push
