name: Unit and Component Tests

on: [pull_request]

jobs:
  jest-and-cypress-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm test
          npm run cypress:component
